### ISSUE TITLE
event-stream appears to break printing in Safari

### ISSUE THREAD

**Issue by fooey** [launchdarkly/js-client#121] opened 2018-11-02 19:59 UTC
We've been trying to debug an issue in our web app with Safari users being unable to print. 

From what we can tell Safari won't print until the page has finished loading, but the event-stream connection is preventing whatever event it's watching for from ever firing. If I disconnect my network, causing the stream to end, the print dialog immediately opens.

Is event-stream possibly breaking print in Safari a known issue with any work around?

**Comment by eli-darkly** [comment] 2018-11-02 20:38
We haven't heard of such an issue (and I don't see any mention of it online), but will try to reproduce this. Do you know what version(s) of Safari?

**Comment by eli-darkly** [comment] 2018-11-02 22:20
I tried reproducing this as follows:

* Created a minimal test app with the JS SDK. It just creates a LD client and then calls `on('change')` to start listening to the event stream.
* Browsed to this app in Safari 11.1.
* Opened the developer console and verified on the Network tab that the event source connection was still active.
* Opened the Print dialog and clicked Print.

The result was that the page printed with no difficulty. After printing, I verified again on the Network tab that the event stream was still connected.

**Comment by fooey** [comment] 2018-11-06 21:35
Sorry I've been slow getting back around to this, but I did a little more debugging on it today with your suggestions.

If I just remove the `on('change')` handler, printing works.

If I add an `off('change')` immediately after the on('change') handler, it works

I threw the instance of the LD object on the window so I could get at it from the console, and I can click print, enter `ld.off('change'`) in the console, and the print window immediately pops. I took a quick little scrunched up video of this as an example: https://www.youtube.com/watch?v=05ZE9XB7zyE

It's very possible there's something in our app just conflicting oddly, and we've just been telling people to use Chrome or Firefox to print, but I thought I should at least try to check upstream with you guys

**Comment by eli-darkly** [comment] 2018-11-08 01:05
Thanks. Well, that does seem pretty definitive that the presence of the active EventSource is causing this... somehow. Clearly something about my test app is different from your environment - I would really love to be able to reproduce this. I've been looking around for any reports of similar behavior in Safari (either with EventSource or with any other kind of persistent connection, like WebSocket) but haven't found anything so far.

**Comment by fooey** [comment] 2018-11-09 17:48
It might help to know this is an EmberJS app, but I haven't been able to think of anything we're doing that could be triggering this bug.

This isn't very high priority for us currently, but I want to try to see if I can put together a minimal demonstration app for debugging sometime, and at least wrap our print functionality with a off/on as a workaround

**Comment by danlec** [comment] 2019-03-14 22:24
I experienced the same issue (caused by LaunchDarkly's use of `EventSource`), reproduced it independently of LaunchDarkly (at https://jsfiddle.net/43ufcxkw/) and have filed a bug for Safari: https://bugs.webkit.org/show_bug.cgi?id=195769

**Comment by eli-darkly** [comment] 2019-03-19 17:23
Oh... this is the first I've heard that it was specifically `window.print()` that was broken. I thought you meant that manually selecting Print did not work either. If it's only `window.print()`, then that explains why I wasn't able to reproduce the bug with my steps above.

**Comment by eli-darkly** [comment] 2019-03-21 21:16
Since this appears to be a Safari issue more than an SDK issue, I'll close it here, but it is now mentioned in our [troubleshooting guide](https://support.launchdarkly.com/hc/en-us/articles/360020264693) and the Support team are aware in case anyone else runs into this.

Thanks for investigating further, @danlec!

**Closed by eli-darkly** 2019-03-21 21:16 UTC

**Comment by iSens** [comment] 2019-05-16 14:42
Hi there, i see this issue is closed, but i am having exactly the same issue in Safari.

Do you have any recommendations ?

document.execCommand('print') doesn't work.

Thanks,
DK

**Comment by eli-darkly** [comment] 2019-05-16 18:23
@iSens Are you also using streaming mode with the SDK (that is, listening for flag changes with `on('change')` or enabling streaming updates with `streaming: true`)?

Also, when you say "this is not a Safari issue"— when I said it seemed to be a Safari issue more than an SDK issue, I was referring to the earlier comment (the same one that suggested `document.execCommand('print')`) that said Safari behaves like this whenever an EventSource object is active, from any code, not just LD. So when you say `windows.print()` is working fine outside of LD, do you mean when an EventSource is active (as in the jsfiddle example)?
